### ISSUE TITLE
Many errors

### ISSUE THREAD

**Issue by lolaswift** [enable3d/threejs-ammojs-webpack-example#1]
npm install went ok.
npm start generated errors:
ERROR in ./node_modules/@enable3d/three-graphics/jsm/flat/physics/physics.js 6:0-98
Module not found: Error: Can't resolve 'matter-js' in 'C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\node_modules\@enable3d\three-graphics\jsm\flat\physics'    
 @ ./node_modules/@enable3d/three-graphics/jsm/flat/index.js 9:0-55 9:0-55
 @ ./node_modules/enable3d/dist/index.js 12:0-60 13:0-26
 @ ./src/index.ts 3:19-38

ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\index.ts
./src/index.ts 50:13-21
[tsl] ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\index.ts(50,14)
      TS2339: Property 'rotation' does not exist on type 'ExtendedObject3D'.

ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\index.ts
./src/index.ts 51:13-21
[tsl] ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\index.ts(51,14)
      TS2339: Property 'rotation' does not exist on type 'ExtendedObject3D'.

ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\standalone.ts
50:13-21
[tsl] ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\standalone.ts(50,14)
      TS2339: Property 'rotation' does not exist on type 'ExtendedObject3D'.

ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\standalone.ts
51:13-21
[tsl] ERROR in C:\Users\lzz\Downloads\threejs-ammojs-webpack-example-main\src\standalone.ts(51,14)
      TS2339: Property 'rotation' does not exist on type 'ExtendedObject3D'.

1 error has detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.53.0 compiled with 5 errors in 2713 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threejs-ammojs-webpack-example@1.0.0 bundle: `webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the threejs-ammojs-webpack-example@1.0.0 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lzz\AppData\Roaming\npm-cache\_logs\2021-10-27T10_45_58_000Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threejs-ammojs-webpack-example@1.0.0 start: `npm run bundle && npm-run-all --parallel webpack serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the threejs-ammojs-webpack-example@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lzz\AppData\Roaming\npm-cache\_logs\2021-10-27T10_45_58_024Z-debug.log

**Comment by shawnThottan** [comment]
Same issue here.. Any idea on how to solve this?

**Comment by yandeu** [comment]
I have just update the example. Please take a look at the new [readme file](https://github.com/enable3d/threejs-ammojs-webpack-example).

**Comment by lolaswift** [comment]
@yandeu many thanks. However, I followed the new readme and got some new errors:
 ./www/scripts/index.ts 281 bytes [built] [code generated]
  ./www/scripts/three.ts 6.1 KiB [built] [code generated] [5 errors]

WARNING in ./node_modules/@enable3d/ammo-physics/dist/convexObjectBreaker.js 40:
107-121
export 'ConvexGeometry' (imported as 'ConvexGeometry') was not found in './exter
nals' (module has no exports)
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 23:0-60 127:37-56
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/ammo-physics/dist/convexObjectBreaker.js 35:0-
52
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\ammo-physics\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 23:0-60 127:37-56
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/ammo-physics/dist/debugDrawer.js 11:0-106
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\ammo-physics\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 22:0-40 139:35-46
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/ammo-physics/dist/externals.js 3:0-78
Module not found: Error: Can't resolve 'three/examples/jsm/geometries/ConvexGeom
etry' in 'D:\aaa\enable3d-webpack\node_modules\@enable3d\ammo-physics\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/convexObjectBreaker.js 36:0-45 40:
107-121
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 23:0-60 127:37-56
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/ammo-physics/dist/physics.js 17:0-86
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\ammo-physics\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/ammo-physics/dist/three-to-ammo.js 12:0-69
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\ammo-physics\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 18:0-126 559:12-29 626:
33-51 629:33-48 632:33-49 635:33-50 638:33-51 641:33-51
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/common/dist/defaultMaterial.js 1:0-44
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\common\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 25:0-68 55:39-54
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/common/dist/extendedGroup.js 6:0-30
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\common\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 12:0-68 13:0-25
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/common/dist/extendedMesh.js 6:0-38
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\common\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 10:0-66 11:0-24
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/common/dist/extendedObject3D.js 6:0-68
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\common\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 8:0-74 9:0-28
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/common/dist/factories.js 17:0-400
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\common\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 20:0-56 135:27-36
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/common/dist/physicsBody.js 7:0-42
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\common\dist'
 @ ./node_modules/@enable3d/ammo-physics/dist/physics.js 7:0-60 754:26-37
 @ ./node_modules/@enable3d/ammo-physics/dist/index.js 3:0-26 3:0-26
 @ ./www/scripts/three.ts 26:23-56
 @ ./www/scripts/index.ts 7:0-18

ERROR in ./node_modules/@enable3d/three-graphics/jsm/csg/_directGeometry.js 2:0-
32
Module not found: Error: Can't resolve 'three' in 'D:\aaa\enable3d-webpack\node_
modules\@enable3d\three-graphics\jsm\csg'
...

**Comment by yandeu** [comment]
Make sure you use node v16 an npm v8

```bash
node -v
npm -v
```

**Comment by lolaswift** [comment]
I just upgrade my node and npm but still the same issue
$ node -v
v16.13.0


$ npm -v
8.1.0

**Comment by yandeu** [comment]
I'm sorry. I don't know why this happens. All my [tests are passing](https://github.com/enable3d/threejs-ammojs-webpack-example/actions/workflows/main.yml?query=branch%3Amain).

**Comment by yandeu** [comment]
Should be fixed now.
